version: '3.8'
services:
  dev-db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: presensi_db
    networks:
      - freecodecamp
networks:
  freecodecamp:
