export enum CodeException {
  CHANGE_PASSWORD_DEFAULT_EXCEPTION = 'CHANGE_PASSWORD_DEFAULT_EXCEPTION',
  ACCOUNT_NOT_FOUND_EXCEPTION = 'ACCOUNT_NOT_FOUND_EXCEPTION',
  WRONG_PASSWORD_EXCEPTION = 'WRONG_PASSWORD_EXCEPTION',
  NEW_PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH_EXCEPTION = 'NEW_PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH',
  PASSWORD_AND_NEW_PASSWORD_ALREADY_SAME_EXCEPTION = 'PASSWORD_AND_NEW_PASSWORD_ALREADY_SAME',
  WRONG_IMEI_EXCEPTION = 'WRONG_IMEI_EXCEPTION',
  ACCOUNT_IS_INACTIVE_EXCEPTION = 'ACCOUNT_IS_INACTIVE_EXCEPTION',
  VALIDATION_ERROR_EXCEPTION = 'VALIDATION_ERROR_EXCEPTION',
  EMAIL_ALREADY_EXISTS_EXCEPTION = 'EMAIL_ALREADY_EXISTS_EXCEPTION',
  PROGRAM_STUDI_NOT_FOUND_EXCEPTION = 'PROGRAM_STUDI_NOT_FOUND_EXCEPTION',
  PROGRAM_STUDI_ALREADY_AXISTS_EXCEPTION = 'PROGRAM_STUDI_ALREADY_AXISTS_EXCEPTION',
}
